script: bundle exec rake test
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
before_install:
  - gem update --system
  - gem --version
env:
  - RAILS=3.2.11
before_script:
  - psql -c "CREATE USER wrburgess WITH PASSWORD 'league';" -U postgres
branches:
  only:
    - master