language:
  - ruby
rvm:
  - 2.0.0
env:
  - RAILS=4.0.0
  - DB=postgresql
  - SECRET_KEY_BASE='travis-secret-key'
branches:
  only:
    - master
before_script:
  - psql -c 'create database league_test' -U postgres
  - 'rake db:migrate'