defaults: &defaults
  app_name: "league-server"
  app_server: "Default"
  app_license: "All Rights Reserved"
  app_season: 2014
  app_periods: 25
  app_alias_group: "league"
  app_alias_roster: "team"
  app_alias_player_team: "school"
  app_alias_player_conference: "conference"
  app_alias_period: "week"
  app_alias_game: "game"
  app_alias_season: "season"
  app_alias_playoff: "playoff"
  app_alias_final: "championship"
  app_game_types:
    - "regular"
    - "playoff"
    - "final"
  redis_host: localhost
  redis_port: 6379
  redis_password:
  mailer_from: "Randy Burgess <wrburgess@gmail.com>"
  mailer_address: "smtp.gmail.com"
  mailer_port: 587
  mailer_domain: "gmail.com"
  mailer_user_name: <%= ENV["MAILER_USERNAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_authentication: "plain"
  mailer_enable_starttls_auto: true

test:
  <<: *defaults
  app_server: "Test"

development:
  <<: *defaults
  app_server: "Development"

staging:
  <<: *defaults
  app_server: "Staging"
  redis_host: <%= ENV["REDIS_HOST"] %>
  redis_port: <%= ENV["REDIS_PORT"] %>
  redis_password: <%= ENV["REDIS_PASSWORD"] %>

production:
  <<: *defaults
  app_server: "Production"
  redis_host: <%= ENV["REDIS_HOST"] %>
  redis_port: <%= ENV["REDIS_PORT"] %>
  redis_password: <%= ENV["REDIS_PASSWORD"] %>