defaults: &defaults
  # app
  app_name: 'League'
  app_server: 'Default'
  app_license: 'All Rights Reserved'
  app_season: 2013
  # redis
  redis_host: localhost
  redis_port: 6379
  redis_password:
  # mailer
  mailer_from: 'League Mailer <no-reply@jbrb.com>'
  mailer_address: 'smtp.mandrillapp.com'
  mailer_port: 587
  mailer_domain: 'heroku.com'
  mailer_user_name: <%= ENV['MANDRILL_USERNAME'] %>
  mailer_password: <%= ENV['MANDRILL_APIKEY'] %>
  mailer_authentication: :plain
  mailer_enable_starttls_auto: true

test:
  <<: *defaults
  app_server: 'League Test'

development:
  <<: *defaults
  app_server: 'League Dev'

staging:
  <<: *defaults
  app_server: 'League Stage'
  redis_host: <%= ENV['REDIS_HOST'] %>
  redis_port: <%= ENV['REDIS_PORT'] %>
  redis_password: <%= ENV['REDIS_PASSWORD'] %>

production:
  <<: *defaults
  app_server: 'League Prod'
  redis_host: <%= ENV['REDIS_HOST'] %>
  redis_port: <%= ENV['REDIS_PORT'] %>
  redis_password: <%= ENV['REDIS_PASSWORD'] %>