defaults: &defaults
  # app
  app_name: "league-server"
  app_server: "Default"
  app_license: "All Rights Reserved"
  app_season: 2013
  # redis
  redis_host: localhost
  redis_port: 6379
  redis_password:
  # mailer
  mailer_from: "Randy Burgess <wrburgess@gmail.com>"
  mailer_address: "smtp.gmail.com"
  mailer_port: 587
  mailer_domain: "gmail.com"
  mailer_user_name: <%= ENV["MAILER_USERNAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_authentication: "plain"
  mailer_enable_starttls_auto: true
  group_alias: "league"
  roster_alias: "team"
  player_team_alias: "school"
  player_conference_alias: "conference"
  period_alias: "week"
  season_alias: "season"

test:
  <<: *defaults
  app_server: "Test"

development:
  <<: *defaults
  app_server: "Development"

staging:
  <<: *defaults
  app_server: "Staging"
  redis_host: <%= ENV["REDIS_HOST"] %>
  redis_port: <%= ENV["REDIS_PORT"] %>
  redis_password: <%= ENV["REDIS_PASSWORD"] %>

production:
  <<: *defaults
  app_server: "Production"
  redis_host: <%= ENV["REDIS_HOST"] %>
  redis_port: <%= ENV["REDIS_PORT"] %>
  redis_password: <%= ENV["REDIS_PASSWORD"] %>