development:
  adapter: postgresql
  host: localhost
  username: [username] #replace
  password: 
  database: league-server-dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username: [username] #replace
  password: 
  database: league-server-test
  pool: 5
  timeout: 5000