development:
  adapter: postgresql
  host: localhost
  username: wrburgess
  password:
  database: league_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username: wrburgess
  password:
  database: league_test
  pool: 5
  timeout: 5000

sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: league_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: league_<%= Rails.env %>
  min_messages: ERROR
